---
- name: Verify
  hosts: all
  become: yes
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Check if amq-broker service is started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["amq-broker.service"]["state"] == "running"
          - ansible_facts.services["amq-broker.service"]["status"] == "enabled"

    - name: Read content of logs
      ansible.builtin.slurp:
        src: /var/log/activemq/amq-broker/artemis.log
      register: slurped_log

    - name: Check status
      ansible.builtin.assert:
        that:
          - "'Server is now live' in slurped_log.content|b64decode or 'Server is now active' in slurped_log.content|b64decode"
        quiet: true
        fail_msg: "Service failed to start correctly"

    - name: Check ownership
      ansible.builtin.stat:
        path: /opt/amq/amq-broker/bin/
      register: broker_bin

    - name: Check ownership
      ansible.builtin.assert:
        that:
          - "broker_bin.stat.pw_name == 'amq-broker'"
        quiet: true
        fail_msg: "Wrong ownership of instance directories"
