---
- name: Determine JAVA_HOME for selected JVM RPM
  ansible.builtin.set_fact:
    rpm_java_home: "/etc/alternatives/jre_{{ activemq_jvm_package | regex_search('(?<=java-)[0-9.]+') }}"

- name: "Ensure systemd unit override directory exists"
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ activemq.instance_name }}.d/"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: "Configure sysconfig file for {{ activemq.instance_name }} {{ activemq.service_name }} service"
  become: true
  ansible.builtin.template:
    src: amq_broker.sysconfig.j2
    dest: "/etc/sysconfig/{{ activemq.instance_name }}"
    owner: root
    group: root
    mode: '0644'
  vars:
    activemq_rpm_java_home: "{{ rpm_java_home }}"
    activemq_logger_opts: "{{ '-Dlog4j.configurationFile=' + activemq_logger_config_template | basename | regex_replace('[.]j2$', '')\
                              if activemq_logger_config_keep_name and activemq_logger_config_template != 'log4j2.properties.j2' }}"
    activemq_jmx_opts: "{{ '-javaagent:/usr/share/java/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=0.0.0.0:' + \
                           activemq_jmx_exporter_port + ':' + activemq_jmx_exporter_config_path if activemq_jmx_exporter_enabled else '' }}"
  notify:
    - restart amq_broker

- name: "Configure systemd unit file for {{ activemq.instance_name }} {{ activemq.service_name }} service"
  ansible.builtin.template:
    src: "{{ activemq_service_override_template | default('amq_broker.service.j2', true) }}"
    dest: "/etc/systemd/system/{{ activemq.instance_name }}.service"
    owner: root
    group: root
    mode: '0644'
  become: true
  register: systemdunit
  notify:
    - restart amq_broker

- name: "Check instance directory: {{ activemq_dest }}/{{ activemq.instance_name }}"
  ansible.builtin.stat:
    path: "{{ activemq_dest }}/{{ activemq.instance_name }}/bin"
  register: instance_directory
  become: true

- name: "Generate artemis configuration for: {{ activemq_dest }}/{{ activemq.instance_name }}"
  ansible.builtin.include_tasks: configure_artemis.yml
  when:
    - not instance_directory.stat.exists

- name: "Create instance {{ activemq.instance_name }} of {{ activemq.service_name }}"
  ansible.builtin.command:
    cmd: "{{ activemq.home }}/bin/artemis create {{ activemq.instance_home }} {{ activemq_options }}"
    creates: "{{ activemq.instance_home }}/bin/artemis-service"
  environment:
    PATH: "{{ rpm_java_home | default(activemq_rpm_java_home, true) }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    JAVA_HOME: "{{ rpm_java_home }}"
  become: true
  become_user: "{{ activemq_service_user }}"
  register: broker_created
  when:
    - not instance_directory.stat.exists

- name: "Configure custom broker.xml file for {{ activemq.instance_name }}"
  ansible.builtin.template:
    src: "{{ activemq_config_override_template }}"
    dest: "{{ activemq.instance_home }}/etc/broker.xml"
    owner: "{{ activemq_service_user }}"
    group: "{{ activemq_service_group }}"
    mode: '0644'
  when: activemq_config_override_template != ''
  become: true
  notify:
    - restart amq_broker
