---
### required variables


### internal variables
activemq:  # noqa var-naming false positive
  home: "{{ activemq_installdir }}"
  user_home: "{{ activemq_service_user_home }}"
  version: "{{ activemq_version }}"
  download_url: "{{ activemq_download_url }}"
  bundle: "{{ activemq_archive }}"
  name: "{{ activemq_name }}"
  service_name: "{{ activemq_service_name }}"
  instance_name: "{{ activemq_instance_name }}"
  instance_home: "{{ activemq_dest }}/{{ activemq_instance_name }}"
  config_xsd: "https://github.com/apache/activemq-artemis/raw/{{ activemq_version }}/artemis-server/src/main/resources/schema/artemis-configuration.xsd"
  server_xsd: "https://github.com/apache/activemq-artemis/raw/{{ activemq_version }}/artemis-server/src/main/resources/schema/artemis-server.xsd"
  package_list: "{{ activemq_base_package_list + [activemq_jvm_package] + ([activemq_jmx_exporter_package] if activemq_jmx_exporter_enabled else []) }}"
  prometheus_package: "{{ 'com.redhat.amq.broker.' if amq_broker_enable is defined and amq_broker_enable and activemq_version.split('.')[1] | int >= 11 else 'org.apache.activemq.artemis.' }}"

activemq_base_package_list:
  - unzip
  - iproute
  - sed
  - procps-ng
  - initscripts
  - libaio
  - python3-lxml
  - tzdata-java

activemq_core_configuration_list:
  - persistence_enabled
  - persist_id_cache
  - id_cache_size
  - journal_type
  - paging_directory
  - bindings_directory
  - journal_directory
  - large_messages_directory
  - journal_datasync
  - journal_min_files
  - journal_pool_files
  - journal_device_block_size
  - journal_file_size
  - journal_buffer_timeout
  - journal_max_io
  - configuration_file_refresh_period
  - global_max_messages
  - global_max_size
  - password_codec
