---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  ci:
    uses: ansible-middleware/github-actions/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      fqcn: 'middleware_automation/amq'
      molecule_tests: >-
        [ "default", "static_cluster", "amq_upgrade", "mask_passwords", "custom_xml" ]
